const GET_SINGER_LIST = 'GET_SINGER_LIST';
const REQUEST_SINGER_LIST = 'REQUEST_SINGER_LIST'
const GET_HOT_SINGER_LIST = 'GET_HOT_SINGER_LIST'
const REQUEST_HOT_SINGER_LIST = 'REQUEST_HOT_SINGER_LIST';
export {
  GET_HOT_SINGER_LIST,
  GET_SINGER_LIST,
  REQUEST_HOT_SINGER_LIST ,
  REQUEST_SINGER_LIST
}