const GET_SINGER_LIST = 'GET_SINGER_LIST';
const REQUEST_SINGER_LIST = 'REQUEST_SINGER_LIST'
const GET_HOT_SINGER_LIST = 'GET_HOT_SINGER_LIST'
const REQUEST_HOT_SINGER_LIST = 'REQUEST_HOT_SINGER_LIST';
const CHANGE_SINGER_PIVOT = 'CHANGE_SIGNER_PIVOT'
const SCROLL_ACTION = 'SCROLL_ACTION'
export {
  GET_HOT_SINGER_LIST,
  GET_SINGER_LIST,
  REQUEST_HOT_SINGER_LIST ,
  REQUEST_SINGER_LIST,
  CHANGE_SINGER_PIVOT,
  SCROLL_ACTION
}